baseURL: "/"
languageCode: "en-us"
title: "Porfolio Markevytch Taras"
theme: "hugo-profile"
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/HTP_5873.jpg"
  name: "Taras MARKEVYTCH"
  namecolor: 00EDF0
  profession: "Développeur Web Front-End"
  github: "https://github.com/TarasMARKEVYTCH"
  linkedin: "https://www.linkedin.com/in/taras-markevytch-3601361b9"
  instagram: "https://www.instagram.com/mark.tariel"
  facebook: "https://facebook.com/taras.markevytch"

  # About
  disable_about: false
  descripe_l1_person: "Bonjour, je m'appele Taras. D'origine ukrainienne, je suis en France depuis 2012. J'ai servi à la Légion étrangère de 2012 à 2021. Développeur front-end avec 2 ans d’expérience, passionné par le monde du numérique, j’ai commencé à coder et m’auto-former au développement web sur les plateformes tels que OpenClassRoom, FreeCode- Camp, Udemy, suivi d’une formation Développeur Web à l’AFPA où j’ai obtenu mon diplome BAC+2 en développement web. Polyvalent, je maîtrise les différentes étapes techniques de la création d’une application web. J’ai soif d’apprendre et je souhaite apporter mes compétences à votre entreprise."
  descripe_l2_person: "Je vous invite à jeter un coup d'œil aux projets que j'ai réalisés pendant mes études, que vous pouvez trouver [ici](#projects)."
  skills:
    - name: HTML/JavaScript
      percentage: 90
    - name: CSS/SCSS/SASS
      percentage: 90
    - name: TailWindCss/Bootstrap 5
      percentage: 90
    - name: TypeScript
      percentage: 70
    - name: PHP
      percentage: 35
    - name: NodeJs
      percentage: 40
    - name: THREE.js
      percentage: 30
    - name: Angular
      percentage: 70
    - name: VueJs 3
      percentage: 30

  otherSkills:
    - name: Go
    - name: GIT
    - name: SQL
    - name: ExpressJs
    - name: AngularJs

  softskills:
    - name: Rigueur
    - name: Autonomie
    - name: Gestion du stress
    - name: Esprit d'équipe
    - name: Capacité d'adaptation

  languages:
    - name: Anglais
    - name: Français
    - name: Russe
    - name: Ukrainien

  PersonalInfo:
    - name: Nationalité
        - française
    - name: Permis
        - categories B et C

  tech:
    - img: /images/visual-studio-code.svg
    - img: /images/sass-seeklogo.com.svg
    - img: /images/angular-icon.svg
    - img: /images/vuejs-seeklogo.com.svg
    - img: /images/nodejs-seeklogo.com.svg
    - img: /images/bootstrap-seeklogo.com.svg
    - img: /images/git-seeklogo.com.svg
    - img: /images/figma-seeklogo.com.svg
    - img: /images/adobe-photoshop-seeklogo.com.svg
    - img: /images/adobe-indesign-seeklogo.com.svg

  # Experience
  disable_experience: false
  experience:
    - company: "ARGO"
      # id: "Kepi Blanc"   // use this, when you want to change the id(used for navigation)
      role: "Développeur web front-end"
      startdate: AVRIL 2022
      enddate: Présent
      featuredpoints:
        - point: Maintenance et développement des modules pour CRM/LIBRARY/EDITEUR/VIEWER avec framework Angular et AngularJs;
        - point: Développement d'outils d'interaction avec la réalité augmentée et les objets 3D;
        - point: Correction des bugs;
        - point: Intégration continue;
        - point: Élaboration de tests unitaires;
    - company: "MEDAE"
      # id: "Kepi Blanc"   // use this, when you want to change the id(used for navigation)
      role: "Stagiaire développeur Web Junior"
      startdate: Novembre 2021
      enddate: Février 2022
      featuredpoints:
        - point: Création des pages du site vitrine;
        - point: Maintenance coté serveur du site "Medae.co";
    - company: "LEGION-ETRANGERE-1RE"
      # id: "Kepi Blanc"   // use this, when you want to change the id(used for navigation)
      role: 'Photographe à "Kepi Blanc"'
      startdate: Novembre 2012
      enddate: Juin 2021
      featuredpoints:
        - point: Prise de vues numériques.
        - point: Traitement des images à l'aide des logiciels ADOBE.
  # Education
  disable_education: false
  education:
    - degree: "BAC+2"
      branch: "Formation développeur Web et Web Mobile"
      university: "AFPA"
      startedyear: "2021"
      graduation: "à present"
    - degree: "FACQ"
      branch: "Photographie"
      university: "Êcole des métiers de l'image à Paris"
      startedyear: "2019"
      graduation: "2019"
    - degree: "Bac +3"
      branch: "Faculté de droit"
      university: "Université d'État des affaires intérieures de Lviv"
      startedyear: "2007"
      graduation: "2010"

  # Projects
  disable_projects: false
  projects:
    - name: "Shaders"
      img: /images/three-js-icon.svg
      githublink: "https://github.com/TarasMARKEVYTCH/shaders-project"
      featuredlink: "/"
      description: "Un projet de création de shaders personnalisés."
      link: "https://shaders-project-iota.vercel.app/shaders"
    - name: "Cadeu NOËL"
      img: /images/NOEL.png
      githublink: "https://github.com/TarasMARKEVYTCH/cars"
      featuredlink: "/"
      description: "Un jou de tirage au sort des cadeaux pour NOEL entre les amis."
      link: "#"
    - name: "Mini-game en JS"
      img: /images/game.png
      githublink: "https://github.com/TarasMARKEVYTCH/mini-game"
      featuredlink: "/"
      description: "Un mini jeu écrit en JavaScript, CSS et HTML"
      link: "https://mini-game-pi.vercel.app/"
    - name: "Yoga-application"
      img: /images/yoga.png
      githublink: "https://github.com/TarasMARKEVYTCH/yoga-application"
      featuredlink: "/"
      description: "Une mini application web pour l'étirement du corps. Créé pendant l'apprentissage de JavaScript."
      link: "https://yoga-application.vercel.app/"
    - name: "Slide-cards"
      img: /images/slides.png
      githublink: "https://github.com/TarasMARKEVYTCH/slide-cards"
      featuredlink: "/"
      description: 'Exemple d''un "accordéon" réalisé en JS'
      link: "https://slide-cards.vercel.app/"
    - name: "Uber HTML page"
      img: /images/uber.png
      githublink: "https://github.com/TarasMARKEVYTCH/uber"
      featuredlink: "/"
      description: "Un projet créé pendant l'apprentissage du HTML, du CSS et de la résponsive."
      link: "https://uber-rose.vercel.app/"

  # Contact
  disable_contact: false
  contact_content: Ma boîte de réception est toujours ouverte. Que vous ayez une question ou que vous souhaitiez simplement me saluer, je ferai de mon mieux pour vous répondre !
  email: "markevych09@gmail.com"
  tel: "+33637753064"

  # Footer
  socialiconfooter: true
  recentposts: true

  # # Blog
  # showdescription: false
  # tweet: true
